### ISSUE TITLE
Releasing the update branch

### ISSUE THREAD

**Issue by hkaraoguz** [strands-project/soma#68]
@jayyoung @kunzel Should we prepare for releasing the update branch?

**Comment by jayyoung** [comment]
Yep sounds good, just need to talk to Nils about something and I'll add my stuff

**Comment by kunzel** [comment]
yes, that is a good idea. Should we remove soma_pcl_segmentation for this, as it still has a dependency to an unreleased package semantic_segmentation. Also currently, it's not used.

**Comment by jayyoung** [comment]
Yeah that sounds good. I will also purge the old world_state stuff too, and replace it with the new soma_llsd we have been working on. Does anyone know of anything else in the package that can be removed or that needs to be updated?

**Comment by hkaraoguz** [comment]
@jayyoung @kunzel Is soma_geospatial_store needed anymore?

**Comment by kunzel** [comment]
No, I believe you have replaced its functionality by integrating the geo
locations into the soma objects.

**Comment by jayyoung** [comment]
So I have still some things to do with this branch before we release it, but should we maybe target at the latest the end of the week for releasing it? I will add my changes tomorrow morning

**Comment by hkaraoguz** [comment]
@jayyoung I also have some new stuff that will be merged hopefully tomorrow.I think it is reasonable to aim for the end of the week for releasing.

**Comment by hkaraoguz** [comment]
@kunzel @jayyoung I just merged my latest changes with the update branch.

**Comment by nilsbore** [comment]
Any progress on this?

**Comment by hkaraoguz** [comment]
@kunzel @jayyoung @ferdianjovan Are we done with this version? Should we aim to release this by the end of the week?

**Comment by ferdianjovan** [comment]
I am done, so yes, please release this.

**Comment by jayyoung** [comment]
Yep cool by me.

**Comment by hkaraoguz** [comment]
@hawesie It seems the major development has finished in this branch. How can we release this branch?

**Comment by hawesie** [comment]
I just triggered it.

**Comment by hkaraoguz** [comment]
@hawesie I noticed that verison 2.0.0 of the soma release does not have everything from the update branch such as soma_msgs. We have dropped the soma2_msgs and soma_geospatial store but they are in 2.0.0. Moreover some packages such as soma_llsd are not included in the 2.0.0 version if I am not wrong.

**Comment by hawesie** [comment]
Ok, this will require some changes to the releases. @marc-hanheide will a PR to change https://github.com/strands-project/rosdistro/blob/strands-devel/indigo/distribution.yaml#L12937 fix this?

**Comment by marc-hanheide** [comment]
So, just to clarify: You want to change the branch from which you are releasing (again)? I dare to ask why not merging into the current release branch? That would make everything less troublesome. If we were to change the branch then we'd have to do a first release manually, in order to get version tagged and making sure it's all consistent. Also possible. Just making the change @hawesie suggests is likely to fail, but feel free to try it ;-) if you have been good in making sure all the package versions are right and so on it might work.

**Comment by hawesie** [comment]
No, I think they just want to change the set of packages that are released, but from this same branch. Maybe the question is, how do I change which set of packages are released? (and I'll deal with the rest)

**Comment by marc-hanheide** [comment]
Oh, that's easy and all automatic. Just trigger a new release. It will release all the packages in the repository and update the `distribution.yaml` accordingly. But, that said, you need to make sure indeed that the repository only contains packages you want to release. But, it seems you guys are talking about the "update" branch, which cannot easily be merged with "indigo-devel", the current release branch it [seems](https://github.com/strands-project/soma/compare/indigo-devel...strands-project:update?expand=1). Indeed the update branch is not ready for release at the moment. For instance, the `package.xml` of [soma_llsd](https://github.com/strands-project/soma/blob/update/soma_llsd/soma_llsd/package.xml) has `0.0.0` as the current version. All version across the repositories need to be the same, and given the last release version was `2.0.0` (see [here](https://github.com/strands-project/rosdistro/blob/strands-devel/indigo/distribution.yaml#L12953)), they all ought to be at least `2.0.0`, so that a new release can bump them higher than the currently released version. Otherwise, no upgrades will happen on any system, as obviously only older versions are released with new ones. Also, it seems that the new update branch is (at least on git) based on soma1, not soma2. I expect many issues there, but I'd leave them to you.

So, if you really want to release the "update" branch, either merge it into indigo-devel (and solve all the conflicts) or change the release branch. But, the release branch is configured here: https://github.com/strands-project-releases/soma/blob/master/tracks.yaml#L13 and not in `distribution.yaml`. In https://github.com/strands-project/rosdistro/blob/strands-devel/indigo/distribution.yaml#L12957 it defines the branch that jenkins is monitoring to make PR and commit builds. *IF* "update" is your new main development branch, change it, but as I said, I recommend sticking to "indigo-devel" and merge "update" into it. If though it looks as if this could end up being messy: https://github.com/strands-project/soma/compare/indigo-devel...strands-project:update?expand=1 Happy to chat on https://gitter.im/strands-project/soma

**Comment by hawesie** [comment]
Thanks! Ok, I'm handing over to @hkaraoguz

**Comment by nilsbore** [comment]
@hkaraoguz Are you doing this?

**Comment by hkaraoguz** [comment]
@nilsbore Yes i think we are very close to releasing it correctly. Should be ready in a day or two hopefully.

**Comment by hkaraoguz** [comment]
@nilsbore Done!
